@extends('layouts.frontend')
@section('content')

    <h1>prueba</h1>
    <h1>prueba</h1>
    <h1>prueba</h1>
    <h1>prueba</h1>
    <h1>prueba</h1>
    <h1>prueba</h1>
    <h1>prueba</h1>
    <h1>prueba</h1>
    <h1>prueba</h1>
    <h1>prueba</h1>
    <h1>prueba</h1>
    <h1>prueba</h1>
    <h1>prueba</h1>
    <h1>prueba</h1>
    <h1>prueba</h1>
@endsection